### ISSUE TITLE
distance unit is weird

### ISSUE THREAD

**Issue by vyvantic** [etrombly/rgeo#1]
The unit of distance as returned by rgeo::search seems to be euclidean *square* degrees. I think its sqrt ought to be returned, and perhaps even converted to km (using an average circumference for earth).

**Comment by etrombly** [comment]
The intention originally was just to return the closest location as quick as possible, so I guess returning the distance is kind of pointless like you said. I'll probably add a nearest_with_distance and search_with_distance that calculate it correctly. Thanks for bringing it up.

**Comment by etrombly** [comment]
So, this is a little embarrassing. I totally forgot that I already had a branch that I switched to calculating the great circle distance, and just hadn't finished cleaning it up. New version is published, if you want to try it out.

**Comment by vyvantic** [comment]
I tested it against google maps, and the result looks right to me. The unit is in miles now. Thanks!
